[package]
name = "analytics-rs"
version = "0.1.0"
authors = ["Francois Dubois <fdubois@devolutions.net>"]

[dependencies]
curl = "0.4.18"
log = "0.4.5"

[dev-dependencies]
env_logger = "0.5.13"
json = "0.11.13"
sysinfo = "0.6.2"
